development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username: postgres
  password: rkohbkdx

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: postgres
  password: rkohbkdx
