# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e4085fb72ab028307360b97877feb6b6146265eda288d16dcc7770d570be87b9c4ac381cdd443511b265f5d54a5dbcb80350631f06c2efb1387ae1392d7c28f

test:
  secret_key_base: ebacca5cfe26c4f933a86f0359b174ed961d214404238cadfa109e4cba3a50342822beb7e2401c4f28fe9a63980c9b57da8e7fa6fc9aac6fd9fa448a763d3ec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
